### ISSUE TITLE
[C4GT] cQubeChat

### ISSUE THREAD

**Issue by ChakshuGautam** [Sunbird-cQube/cQubeChat#1]
# Project Details
cQubeChat is an intuitive and user-friendly application that allows users to interact with their cQube data using natural language queries. Type in your questions or requests, and SnowChat will generate the appropriate SQL query and return the data you need. No more complex SQL queries or digging through tables - cQubeChat makes it easy to access your data! By bringing data one step closer, cQubeChat empowers users to make data-driven decisions faster and more efficiently, reducing the barriers between users and the insights they seek.

(Taken from [this](https://github.com/kaarthik108/snowChat) implementation)

## Features to be implemented
- [ ] Integrate cQube datasets
- [ ] A standalone application (chat interface) that connects to the cQube that allows for querying of data from cQube and returns the response as a table/big number/chart depending on user request.
- [ ] An autocomplete to suggest users sample queries that they can do.
- [ ] Caching of autocomplete prompts for faster response times.
- [ ] Advanced Analytics: Integrate with popular data visualization libraries like Plotly or Matplotlib to generate interactive visualizations based on the user's queries (AutoGPT).
- [ ] Integrate with cQube Deployment as an optional feature.

### Complexity  
Medium      

### Skills Required 
Python, Streamlit.

## Project size
8 Weeks

## Product Set Up
This project has no setup right now and needs to be done from scratch.

## Acceptance Criteria 
- [ ] e2e Test Caes
- [ ] OpenAPI Spec/Postman Collection
- [ ] Dockerfile for this module

## Milestone
Every document type supported is a milestone.

## Reference
1. [SnowChat](https://github.com/kaarthik108/snowChat)
2. [Text2SQL](https://github.com/ChakshuGautam/Text2SQL)

# C4GT
This issue is nominated for Code for GovTech (C4GT) 2023 edition. 
C4GT is India's first annual coding program to create a community that can build and contribute to global [Digital Public Goods](https://www.codeforgovtech.in/digitalpublicgoods). If you want to use Open Source GovTech to create impact, then this is the opportunity for you! More about C4GT here: https://codeforgovtech.in/

**Comment by Komal-99** [comment]
Hi , I would Like to work and research under this project for C4GT. But I have few queries like from where We can accesst the cQube dataset on which bot should perform sql operations  also If Before implementing exact this project I try working on Normal Chat bot working on voice commands i.e voice to text translation will that be counted under the Proposal for C4GT

**Comment by suveergarg** [comment]
Hi, I am interested in this project. I saw that Text2SQL project already runs with Streamlit. Is the core focus of this project then using those database queries from Text2SQL and presenting them in a user-friendly way or will this project be a separate Streamlit app?

As a initial contribution, I am hoping to write the setup for this project with a basic Streamlit app. To submit a PR, I need to be able to fork this repository. Github does not allow me to fork as long as this is a empty repository.

**Comment by anoushkamishra2803** [comment]
Hi, I wanted to work and research on this project under C4GT. I have run a few projects on Streamlit and have quite the right amount of Python knowledge.
As an initial contribution, I will be requiring your guidance in the same and will be interested in integrating cQube datasets

**Comment by Hansolo1103** [comment]
Hi , I would very much like to contribute to this project as it is a perfect match with my skill set. I am currently working as an intern in building chat-based solutions with the very framework that is needed for the project.
I have experience in Streamlit and flask as well, and integrating the datasets will be a interesting challenge for me.

**Comment by ChakshuGautam** [comment]
Hey guys. Please reach out to me with your proposals on Discord. If you want to contribute before that, please go ahead and share your plans we should be able to come up with a plan for that as well.

**Comment by pooranjoyb** [comment]
Hey @ChakshuGautam . 
I'm a skilled Flask developer with fluent Streamlit experience, and I'm eager to contribute to this wonderful project. My proficiency in integrating Flask and Streamlit is exemplified in my project at [Health-Bridge](https://github.com/pooranjoyb/health-bridge/). By leveraging these technologies, I successfully created a seamless GUI. I believe my expertise makes me a suitable candidate to contribute to your project. I look forward to discussing the details further.

I would be glad if you could provide me Proposal Submission Guidelines. Thanks!

**Comment by jainendra001** [comment]
Hi @ChakshuGautam ,

I'm Jainendra Tripathy, and I am interested in contributing to this project. I'm an AI and ML developer with good hands-on experience in Python, Streamlit..
I have a strong understanding of Python and Streamlit.., and I'm always looking for new ways to learn and grow. I'm also a quick learner and always willing to help.
I'm available to contribute. I'm eager to get started and make a difference. I can help you take this project to the next level.
If you're interested in having me contribute, please let me know. I'm happy to answer any questions you have.
And I am also applying to the C4GT too please consider my application.

Thanks,
Jainendra Tripathy

**Comment by Rishikesh233** [comment]
Hi, I would like to contribute to this project as it is a perfect match for my skill set. I am currently working as an intern in building chat-based solutions with the framework needed for the project.
I have experience in Streamlit, which will be an interesting challenge for me.

**Comment by vandit98** [comment]
Hi @ChakshuGautam
I understand the project and would like to contribute to it. My skillset completely allign with this project. I have used streamlit,sql,docker and python in many projects and i am well versed with all of them.

Thanks 
Vandit Tyagi

**Comment by moreatharvaa** [comment]
> Hey guys. Please reach out to me with your proposals on Discord. If you want to contribute before that, please go ahead and share your plans we should be able to come up with a plan for that as well.

hello, can we collaborate to the project together?

**Comment by Srishti-j18** [comment]
Dear Mentors!!
I have submitted my proposal for [C4GT] cQubeChat #1 and looking forward to learn and contribute .. :)

**Comment by Madhav-2808** [comment]
Hi Everyone ,
I'm Madhav Singh ( https://github.com/Madhav-2808  any suggestions welcomes ) Fresher in Open Source , excited to contribute to this project ; if things go right  :)
